#!/usr/bin/env bash
# Tests for scripts/git/check-commit-msg.sh and .githooks/pre-commit.
# Plain bash, no dependencies; run from anywhere: bash tests/git/test_git_rules.sh
set -uo pipefail

root=$(cd "$(dirname "$0")/../.." && pwd)
check="$root/scripts/git/check-commit-msg.sh"
passed=0; failed=0

expect() {  # $1 = pass|fail, $2 = description, rest = command
    local want=$1 desc=$2; shift 2
    if "$@" >/dev/null 2>&1; then got=pass; else got=fail; fi
    if [ "$got" = "$want" ]; then passed=$((passed + 1))
    else failed=$((failed + 1)); echo "FAIL: $desc (expected $want, got $got)"; fi
}
msg() { printf '%b' "$1" | "$check" -; }
body() { printf '%b' "$1" | "$check" --no-subject -; }

# Conventional Commits subjects
expect pass "plain type"             msg "docs: add design document"
expect pass "type with scope"        msg "feat(policy): add two-threshold gate"
expect pass "breaking change marker" msg "feat(api)!: drop v1 endpoint"
expect pass "subject with body"      msg "fix(classifiers): fall back to rules\n\nLaya timed out."
expect pass "git template comments"  msg "# comment from git\nchore: bump version"
expect fail "no type"                msg "Add design document"
expect fail "unknown type"           msg "feature: add gate"
expect fail "uppercase description"  msg "docs: Add design document"
expect fail "trailing period"        msg "docs: add design document."
expect fail "missing space"          msg "docs:add design document"
expect fail "uppercase scope"        msg "feat(Policy): add gate"
expect fail "over 72 characters"     msg "docs: $(printf 'a%.0s' $(seq 1 70))"
expect fail "fixup commit"           msg "fixup! docs: add design document"

# AI-tool attribution
expect fail "co-author trailer"      msg "docs: add x\n\nCo-Authored-By: Claude <noreply@anthropic.com>"
expect fail "session trailer"        msg "docs: add x\n\nClaude-Session: https://example.com"
expect fail "generated footer in PR" body "## What\n\n🤖 Generated with [Claude Code](https://example.com)"
expect fail "factory droid trailer"  msg "docs: add x\n\nCo-authored-by: factory-droid[bot] <138933559+factory-droid[bot]@users.noreply.github.com>"
expect fail "droid footer in PR"     body "## What\n\nGenerated by Factory Droid"
expect pass "human co-author"        msg "docs: add x\n\nCo-Authored-By: Ana Perez <ana@example.com>"
expect pass "clean PR description"   body "## What\n\nAdds the design document."

# Hooks, run inside a throwaway repository with a primary checkout on main and
# a linked worktree on a feature branch. The fake secrets below are split with
# "" so this file itself never trips the hook it tests.
tmp=$(mktemp -d); trap 'rm -rf "$tmp"' EXIT
repo="$tmp/repo"; wt="$tmp/repo/.worktrees/feature"
git init -q -b main "$repo"
git -C "$repo" -c user.name=t -c user.email=t@example.com commit -q --allow-empty -m "chore: init"
git -C "$repo" worktree add -q "$wt" -b feat/example
hook() {  # $1 = directory, $2 = hook name
    (cd "$1" && "$root/.githooks/$2")
}
staged_in() {  # $1 = directory, $2 = path, $3 = content
    git -C "$1" reset -q 2>/dev/null || true
    mkdir -p "$1/$(dirname "$2")"; printf '%s\n' "$3" > "$1/$2"
    git -C "$1" add "$2" && hook "$1" pre-commit
}
staged() { staged_in "$wt" "$@"; }

# Branch and worktree guards
expect fail "commit on main"                 staged_in "$repo" "src/a.py" "x = 1"
git -C "$repo" reset -q; git -C "$repo" switch -q -c feat/primary
expect fail "commit from primary checkout"   staged_in "$repo" "src/a.py" "x = 1"
git -C "$repo" reset -q; git -C "$repo" switch -q main
push_to() { printf 'refs/heads/x 1111 %s 0000\n' "$1" | hook "$wt" pre-push; }
delete_remote() { printf '(delete) 0000000000000000000000000000000000000000 %s 0000\n' "$1" | hook "$wt" pre-push; }
expect fail "push to main"                   push_to refs/heads/main
expect pass "push feature branch"            push_to refs/heads/feat/example
expect pass "push branch with dots, digits"  push_to refs/heads/docs/v0.2-notes
expect fail "push tool-named branch"         push_to refs/heads/claude/stoic-brown-73h4w3
expect fail "push branch without type"       push_to refs/heads/policy-gate
expect fail "push uppercase branch"          push_to refs/heads/feat/Policy-Gate
expect pass "push a tag"                     push_to refs/tags/v0.2.0
expect pass "delete an odd remote branch"    delete_remote refs/heads/claude/old

# Secret and file guards, in the feature worktree
expect pass "ordinary source file"   staged "src/app.py" "print('hello')"
expect fail "dataset file"           staged "data/customers.csv" "id,name"
expect fail "env file"               staged ".env" "TOKEN=x"
expect fail "model weights"          staged "models/laya.safetensors" "weights"
expect fail "AWS access key id"      staged "src/config.py" "KEY = 'AKIA""ABCDEFGHIJKLMNOP'"
expect fail "private key"            staged "src/key.txt" "-----BEGIN OPENSSH ""PRIVATE KEY-----"
expect fail "AWS secret key name"     staged "src/c.ini" "aws_secret_access""_key = x"
expect pass "env var lookup"         staged "src/settings.py" "key = os.environ['AWS_ACCESS_KEY_ID']"

# Commit size check, in its own throwaway repository. Limits are lowered through
# the environment (3 files, 10 lines) so the fixtures stay tiny.
sz="$tmp/size"
git init -q -b main "$sz"
szgit() { git -C "$sz" -c user.name=t -c user.email=t@example.com "$@"; }
szgit commit -q --allow-empty -m "chore: init"
base=$(git -C "$sz" rev-parse HEAD)
add_commit() {  # $1 = message, rest = "path:lines" pairs
    local message=$1; shift
    local spec
    for spec in "$@"; do
        mkdir -p "$sz/$(dirname "${spec%%:*}")"
        seq 1 "${spec##*:}" > "$sz/${spec%%:*}"
        git -C "$sz" add "${spec%%:*}"
    done
    szgit commit -q -m "$(printf '%b' "$message")"
}
size_check() { (cd "$sz" && COMMIT_MAX_FILES=3 COMMIT_MAX_LINES=10 "$root/scripts/git/check-commit-size.sh" "$@"); }
last_range() { echo "$base..HEAD"; }

add_commit "feat: small" a.py:5 b.py:5
expect pass "small commit"                  size_check "$(last_range)"
add_commit "feat: exactly at the limits" c.py:4 d.py:3 e.py:3
expect pass "commit at the limits"          size_check "HEAD~1..HEAD"
add_commit "feat: too many files" f1:1 f2:1 f3:1 f4:1
expect fail "too many files"                size_check "HEAD~1..HEAD"
expect fail "bad commit inside a range"     size_check "$(last_range)"
add_commit "feat: too many lines" g.py:11
expect fail "too many lines"                size_check "HEAD~1..HEAD"
add_commit "build: lock and generated files are not counted" h.py:2 uv.lock:500 frontend/package-lock.json:500 contracts/tools/x.json:500 tests/fixtures/bank/y.json:500
expect pass "excluded paths ignored"        size_check "HEAD~1..HEAD"
add_commit "feat: bulk move\n\nSize-exception: one indivisible rename of the package" i.py:50
expect pass "size exception with a reason"  size_check "HEAD~1..HEAD"
add_commit "feat: bulk move\n\nSize-exception: ok" j.py:50
expect fail "size exception reason too short" size_check "HEAD~1..HEAD"
expect pass "warn mode exits zero"          size_check --warn "HEAD~1..HEAD"
expect pass "warn mode prints a warning"    bash -c 'cd "$0" && COMMIT_MAX_LINES=10 "$1" --warn HEAD~1..HEAD 2>&1 | grep -q "^warning: commit"' "$sz" "$root/scripts/git/check-commit-size.sh"
expect pass "empty range"                   size_check "HEAD..HEAD"

# The same check inside the pre-push hook: it compares against origin/main.
git -C "$sz" update-ref refs/remotes/origin/main "$base"
push_size() {  # $1 = commit to push
    printf 'refs/heads/feat/x %s refs/heads/feat/x 0000\n' "$1" |
        (cd "$sz" && COMMIT_MAX_FILES=3 COMMIT_MAX_LINES=10 "$root/.githooks/pre-push")
}
expect pass "push a small commit"            push_size "$(git -C "$sz" rev-list --reverse "$base..HEAD" | head -n 1)"
expect fail "push a branch with a big commit" push_size "$(git -C "$sz" rev-parse HEAD)"

echo "$passed passed, $failed failed"
[ "$failed" -eq 0 ]
