"""Generates the JSON Schema tool contracts in ``contracts/tools/`` from the models (TSD-002).

The models in ``contracts.py`` and the tool signatures in ``server.py`` are the source; the
files are generated by ``scripts/export_tool_schemas.py`` and a test fails if they drift, so
the contract an integrator reads is the one the server enforces.
"""

from __future__ import annotations

import json
from datetime import UTC, datetime
from typing import Any

import anyio

from calvino.tools.confirmation import FakeConfirmationVerifier
from calvino.tools.contracts import SCHEMA_MODELS
from calvino.tools.dataset import DatasetAdapter
from calvino.tools.server import create_server
from calvino.tools.service import BankTools

_WRITE_TOOLS = frozenset({"request_cancellation", "retry_payment", "open_investigation"})


def _dump(value: Any) -> str:
    return json.dumps(value, indent=2, sort_keys=True, ensure_ascii=False) + "\n"


def build_contract_files() -> dict[str, str]:
    """Return ``{file name: content}`` for every file in ``contracts/tools/``."""
    files = {
        f"{name}.schema.json": _dump(model.model_json_schema(mode="serialization"))
        for name, model in SCHEMA_MODELS.items()
    }
    empty = {"customers": [], "accounts": [], "entries": []}
    tools = BankTools(
        DatasetAdapter(empty, clock=lambda: datetime(2026, 1, 1, tzinfo=UTC)),
        FakeConfirmationVerifier(),
    )
    server = create_server(tools, lambda ctx: None)

    async def listed() -> list[dict[str, Any]]:
        return [
            {
                "name": t.name,
                "kind": "write" if t.name in _WRITE_TOOLS else "read",
                "description": t.description,
                "input_schema": t.input_schema,
                "output_schema": t.output_schema,
            }
            for t in await server.list_tools()
        ]

    files["tools.json"] = _dump(anyio.run(listed))
    return files
